# Generated by Django 4.2.16 on 2024-10-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pxcp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
